### ISSUE TITLE
When the text is less than 5 words, there is transparency in the last text.

### ISSUE THREAD

**Issue by tpnet** [ronpattern/DisplayTextView#1]
![image](https://user-images.githubusercontent.com/17380722/43383417-81a43596-940d-11e8-9576-505af2a708e7.png)

![image](https://user-images.githubusercontent.com/17380722/43383442-973735d4-940d-11e8-8889-bcf82179a10d.png)

**Comment by tpnet** [comment]
@ronpattern  Hello，Are you there？

**Comment by ronpattern** [comment]
Hello tpnet
I don't know if you are still concerned by this problem but i couln't reproduce it.
Can you tell me if you encounter this problem with the 1.1 version.
If it is the case, i will take a look as soon as possible.
